# Generated by Django 3.2.18 on 2024-02-15 10:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته')),
                ('url', models.TextField(unique=True, verbose_name='آدرس دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان پست')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.SlugField(unique=True, verbose_name='آدرس پست')),
                ('is_active', models.BooleanField(choices=[(False, 'پیش نویس'), (True, 'نمایش عمومی')], default=False)),
                ('is_pin', models.BooleanField(verbose_name='یین شده')),
                ('created_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Articles')),
                ('keyword', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان تگ')),
                ('url', models.TextField(unique=True, verbose_name='آدرس تگ')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('title4', models.CharField(blank=True, max_length=50, null=True)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('link3', models.URLField(blank=True, null=True)),
                ('link4', models.URLField(blank=True, null=True)),
                ('password', models.CharField(blank=True, default='پسورد ندارد.', max_length=50, null=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.articles')),
            ],
        ),
    ]
