# Generated by Django 4.1.6 on 2023-03-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته')),
                ('url', models.URLField(verbose_name='آدرس دسته بندی')),
                ('is_active', models.BooleanField(verbose_name='وضعیت نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تگ')),
                ('url', models.URLField(verbose_name='آدرس تگ')),
                ('is_active', models.BooleanField(verbose_name='وضعیت نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان پست')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', models.TextField(verbose_name='محتوای پست')),
                ('url', models.URLField(verbose_name='آدرس پست')),
                ('is_active', models.BooleanField(verbose_name='وضعیت نمایش')),
                ('is_pin', models.BooleanField(verbose_name='یین شده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ابجاد پست ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت پست')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categories', models.ManyToManyField(to='Post.articlecategories', verbose_name='دسته ها')),
                ('tags', models.ManyToManyField(to='Post.articletags', verbose_name='تگ ها')),
            ],
        ),
    ]
