# Generated by Django 3.2.18 on 2024-01-31 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته')),
                ('url', models.TextField(unique=True, verbose_name='آدرس دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان پست')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.SlugField(verbose_name='آدرس پست')),
                ('is_active', models.BooleanField(choices=[(False, 'پیش نویس'), (True, 'نمایش عمومی')], default=False)),
                ('is_pin', models.BooleanField(verbose_name='یین شده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ابجاد پست ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Articles')),
                ('keyword', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تگ')),
                ('url', models.TextField(unique=True, verbose_name='آدرس تگ')),
            ],
        ),
    ]
