# Generated by Django 4.1.6 on 2023-03-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategories',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='articletags',
            name='is_active',
        ),
    ]
