# Generated by Django 3.2.18 on 2024-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('title4', models.CharField(blank=True, max_length=50, null=True)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('link3', models.URLField(blank=True, null=True)),
                ('link4', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
