# Generated by Django 3.2.18 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
