# Generated by Django 4.1.6 on 2023-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_remove_articlecategories_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletags',
            name='url',
            field=models.URLField(unique=True, verbose_name='آدرس تگ'),
        ),
    ]
