# Generated by Django 3.2.18 on 2024-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_articles_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='previewtext',
            field=models.TextField(default='sdfsd', max_length=500),
            preserve_default=False,
        ),
    ]
