# Generated by Django 3.2.18 on 2024-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_downloadbox_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadbox',
            name='password',
            field=models.CharField(blank=True, default='پسورد ندارد.', max_length=50, null=True),
        ),
    ]
