# Generated by Django 3.2.18 on 2024-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_articles_previewtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadbox',
            name='Post',
        ),
        migrations.AddField(
            model_name='articles',
            name='downloadbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.downloadbox'),
        ),
    ]
