# Generated by Django 4.1.6 on 2023-03-21 19:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_articlecategories_url_alter_articles_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='محتوای پست'),
        ),
    ]
