# Generated by Django 4.1.6 on 2023-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_articles_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Post.articlecategories', verbose_name='دسته ها'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Post.articletags', verbose_name='تگ ها'),
        ),
    ]
