# Generated by Django 4.1.6 on 2023-03-25 07:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_alter_articles_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='keyword',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
