# Generated by Django 4.1.6 on 2023-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_articles_keyword_alter_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'پیش نویس'), (True, 'نمایش عمومی')], default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='Post.articletags', verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.SlugField(verbose_name='آدرس پست'),
        ),
    ]
