# Generated by Django 3.2.18 on 2024-02-15 10:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان پست')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.SlugField(verbose_name='آدرس صفحه')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ابجاد پست ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت پست')),
                ('keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(choices=[(False, 'پیش نویس'), (True, 'نمایش عمومی')], default=False)),
            ],
        ),
    ]
