# Generated by Django 3.2.18 on 2024-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_rename_title_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_Displayed',
            field=models.BooleanField(default=0),
        ),
    ]
