# Generated by Django 3.2.18 on 2024-02-15 10:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0, verbose_name='هزینه')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان پست')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.SlugField(verbose_name='آدرس محصول')),
                ('is_active', models.BooleanField(choices=[(False, 'پیش نویس'), (True, 'نمایش عمومی')], default=False)),
                ('is_pin', models.BooleanField(verbose_name='یین شده')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(default=0, verbose_name='قیمت محصول')),
                ('fprice', models.IntegerField(default=0, verbose_name='قیمت اولیه محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0, verbose_name='هزینه')),
                ('is_success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
