# Generated by Django 3.2.18 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdownload',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='linkdownload',
            name='file',
            field=models.FileField(upload_to='product/file'),
        ),
    ]
