# Generated by Django 3.2.18 on 2024-03-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20240219_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdownload',
            name='Product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.product'),
        ),
    ]
