# Generated by Django 3.2.18 on 2024-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_linkdownload_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fprice',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت اولیه محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت محصول'),
        ),
    ]
