# Generated by Django 3.2.18 on 2024-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='PublicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(default='isgame.ir')),
                ('email', models.EmailField(default='admin@gmail.com', max_length=254)),
                ('logoIcon', models.ImageField(blank=True, null=True, upload_to='SiteSetting/Logo')),
                ('logoSite', models.ImageField(blank=True, null=True, upload_to='SiteSetting/Logo')),
                ('post_per_homePage', models.IntegerField(default=10, max_length=3)),
                ('post_per_cat', models.IntegerField(default=10, max_length=3)),
                ('is_Register', models.BooleanField(default=1)),
                ('is_Comment', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('aparat', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
