# Generated by Django 4.1.6 on 2023-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='is_setting',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
