# Generated by Django 3.2.18 on 2024-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
