# Generated by Django 4.1.6 on 2023-04-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SiteModule', '0002_alter_socialmedialink_is_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='pinterest',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
