# Generated by Django 3.2.18 on 2023-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0003_remove_socialmedialink_pinterest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
