# Generated by Django 3.2.18 on 2023-12-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0004_publicsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='is_setting',
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='is_Register',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='logoIcon',
            field=models.ImageField(blank=True, null=True, upload_to='SiteSetting/Logo'),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='logoSite',
            field=models.ImageField(blank=True, null=True, upload_to='SiteSetting/Logo'),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='post_per_cat',
            field=models.IntegerField(default=10, max_length=3),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='post_per_homePage',
            field=models.IntegerField(default=10, max_length=3),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='socialLinks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteModule.socialmedialink'),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='url',
            field=models.URLField(default='isgame.ir'),
        ),
    ]
