# Generated by Django 3.2.18 on 2024-01-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0005_auto_20231229_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsettings',
            name='is_Comment',
            field=models.BooleanField(default=1),
        ),
    ]
