# Generated by Django 4.1.6 on 2023-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_incorrect_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrect_attempts',
            name='browser',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incorrect_attempts',
            name='device',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incorrect_attempts',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incorrect_attempts',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incorrect_attempts',
            name='is_ness',
            field=models.BooleanField(default=True),
        ),
    ]
