# Generated by Django 4.1.6 on 2023-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tokenauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
