# Generated by Django 3.2.18 on 2023-12-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='Profile'),
        ),
    ]
