# Generated by Django 4.1.6 on 2023-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=50)),
                ('sort', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
                ('icon_name', models.CharField(max_length=50, null=True)),
                ('icon_color', models.CharField(max_length=50, null=True)),
                ('place_menu', models.CharField(choices=[('MN1', 'چایگاه هدر اول'), ('MN2', 'جایگاه هدر دوم'), ('MN3', 'جایگاه هدر سوم'), ('FN1', 'جایگاه فوتر اول'), ('FN2', 'جایگاه فوتر دوم'), ('SC1', 'شبکه های اجتماعی')], max_length=50)),
            ],
        ),
    ]
