# Generated by Django 3.2.18 on 2024-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url', models.TextField(max_length=100, verbose_name='آدرس')),
                ('sort', models.IntegerField(verbose_name='فیلد ترتیب')),
                ('is_active', models.BooleanField(default=1, verbose_name='وضعیت نمایش')),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام آیکون')),
                ('icon_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ ایکون')),
                ('place_menu', models.CharField(choices=[('MN1', 'جایگاه هدر اول'), ('MN2', 'جایگاه هدر دوم'), ('MN3', 'جایگاه هدر سوم'), ('FN1', 'جایگاه فوتر اول'), ('FN2', 'جایگاه فوتر دوم'), ('SC1', 'شبکه های اجتماعی')], max_length=50, verbose_name='جایگاه منو')),
            ],
        ),
    ]
