# Generated by Django 4.1.6 on 2023-03-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon_color',
            field=models.CharField(max_length=50, null=True, verbose_name='رنگ ایکون'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon_name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام آیکون'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='وضعیت نمایش'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='place_menu',
            field=models.CharField(choices=[('MN1', 'چایگاه هدر اول'), ('MN2', 'جایگاه هدر دوم'), ('MN3', 'جایگاه هدر سوم'), ('FN1', 'جایگاه فوتر اول'), ('FN2', 'جایگاه فوتر دوم'), ('SC1', 'شبکه های اجتماعی')], max_length=50, verbose_name='جایگاه منو'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(verbose_name='فیلد ترتیب'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(max_length=50, verbose_name='آدرس'),
        ),
    ]
