# Generated by Django 4.1.6 on 2023-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_menu_icon_color_alter_menu_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.TextField(max_length=100, verbose_name='آدرس'),
        ),
    ]
