# Generated by Django 3.2.18 on 2024-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
