# Generated by Django 3.2.18 on 2024-03-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='come',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comment.comment'),
        ),
    ]
